### ISSUE TITLE
Neovim Support?

### ISSUE THREAD

**Issue by UnrealApex** [vim/killersheep#6]
It would be nice if there could be Neovim support for this plugin or a port. Would it be possible in your opinion?

**Comment by chrisbra** [comment]
I guess contributions are always welcome :)

**Comment by brammool** [comment]
> It would be nice if there could be Neovim support for this plugin or a
> port. Would it be possible in your opinion?

I don't use Neovim, but it probably lacks some essential features.  I
don't suppose it has sound support, but that could be done with an
external process probably.  It also heavily depend on popup windows.
Does Neovim have those?

-- 
hundred-and-one symptoms of being an internet addict:
10. And even your night dreams are in HTML.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by seandewar** [comment]
@UnrealApex Maybe https://github.com/seandewar/killersheep.nvim is of interest to you? :wink:

**Comment by UnrealApex** [comment]
> I don't use Neovim, but it probably lacks some essential features. I don't suppose it has sound support, but that could be done with an external process probably. It also heavily depend on popup windows. Does Neovim have those?

Hmm, for sound, I'm not sure if Neovim ever had support for that. As for popup windows, probably. I think @seandewar might have a better idea about compatability.

**Comment by UnrealApex** [comment]
@seandewar 's port is pretty nice. I guess this will do.
